{% set name = "rich" %}
{% set version = "13.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Textualize/{{ name }}/archive/refs/tags/v{{ version  }}.tar.gz
  sha256: 94f7240312afb70f1055bd434fed7df0bda086533c93e04bf161b159fcc9fcf7 

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<37]

requirements:
  host:
    - pip
    - python
    - poetry-core 1.5
  run:
    - markdown-it-py >=2.2.0,<3.0.0
    - pygments >=2.13.0,<3.0.0
    - python
    - typing_extensions >=4.0.0,<5.0.0  # [py<39]
  run_constrained:
    - ipywidgets >=7.5.1,<9
test:
  imports:
    - rich
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Textualize/rich
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rich is a Python library for rich text and beautiful formatting in the terminal.
  description: |
    Rich is a Python library for rich text and beautiful formatting
    in the terminal.The Rich API makes it easy to add color and style to
    terminal output. Rich can also render pretty tables, progress bars,
    markdown, syntax highlighted source code, tracebacks, and more — out
    of the box.
  doc_url: https://rich.readthedocs.io/en/latest/
  dev_url: https://github.com/Textualize/rich

extra:
  recipe-maintainers:
    - jan-janssen
    - willmcgugan
