{% set name = "rich" %}
{% set version = "13.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9be308cb1fe2f1f57d67ce99e95af38a1e2bc71ad9813b0e247cf7ffbcc3a432

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: True  # [py<37]

requirements:
  host:
    - pip
    - python
    - poetry-core 1.5
  run:
    - markdown-it-py >=2.2.0
    - pygments >=2.13.0
    - python
    - typing_extensions >=4.0.0  # [py<39]
  run_constrained:
    - ipywidgets >=7.5.1
test:
  imports:
    - rich
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/willmcgugan/rich
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rich is a Python library for rich text and beautiful formatting in the terminal.
  description: |
    Rich is a Python library for rich text and beautiful formatting
    in the terminal.The Rich API makes it easy to add color and style to
    terminal output. Rich can also render pretty tables, progress bars,
    markdown, syntax highlighted source code, tracebacks, and more — out
    of the box.
  doc_url: https://rich.readthedocs.io/en/latest/
  dev_url: https://github.com/willmcgugan/rich

extra:
  recipe-maintainers:
    - jan-janssen
    - willmcgugan
