{% set name = "rich" %}
{% set version = "13.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d11b9b8dd03868f09b4fffadc84a6a8cda574e40dc90821bd845720ebb8e89c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation
  skip: True  # [py<37]

requirements:
  host:
    - pip
    - setuptools
    - wheel
    - python
    - poetry-core >=1.0.10
  run:
    - markdown-it-py >=2.2.0,<3.0.0
    - commonmark >=0.9.0,<0.10.0
    - dataclasses >=0.7,<0.9
    - pygments >=2.13.0,<3.0.0
    - python
    - typing_extensions >=4.0.0,<5.0.0

test:
  imports:
    - rich
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/willmcgugan/rich
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Rich is a Python library for rich text and beautiful formatting in the terminal.
  description: |
    Rich is a Python library for rich text and beautiful formatting
    in the terminal.The Rich API makes it easy to add color and style to
    terminal output. Rich can also render pretty tables, progress bars,
    markdown, syntax highlighted source code, tracebacks, and more — out
    of the box.
  doc_url: https://rich.readthedocs.io/en/latest/
  dev_url: https://github.com/willmcgugan/rich

extra:
  recipe-maintainers:
    - jan-janssen
    - willmcgugan
